// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.biznessapps.localization;

import android.util.SparseArray;

public final class KeysMap
{

    private static final SparseArray keysConverter;

    public KeysMap()
    {
    }

    public static String getValue(int i)
    {
        return (String)keysConverter.get(i);
    }

    static 
    {
        keysConverter = new SparseArray();
        keysConverter.put(com.biznessapps.layout.R.string.about, "About");
        keysConverter.put(com.biznessapps.layout.R.string.account, "Account");
        keysConverter.put(com.biznessapps.layout.R.string.accounts, "Accounts");
        keysConverter.put(com.biznessapps.layout.R.string.activity, "Activity");
        keysConverter.put(com.biznessapps.layout.R.string.add_to_calendar, "Add to Cal");
        keysConverter.put(com.biznessapps.layout.R.string.add_caption, "Add a caption");
        keysConverter.put(com.biznessapps.layout.R.string.add_photo, "Add Photo");
        keysConverter.put(com.biznessapps.layout.R.string.add_note, "Add Note");
        keysConverter.put(com.biznessapps.layout.R.string.add_score, "Add Score");
        keysConverter.put(com.biznessapps.layout.R.string.album, "Album:");
        keysConverter.put(com.biznessapps.layout.R.string.albums, "Albums");
        keysConverter.put(com.biznessapps.layout.R.string.alert, "Alert");
        keysConverter.put(com.biznessapps.layout.R.string.all, "All");
        keysConverter.put(com.biznessapps.layout.R.string.all_tracks_title, "All Tracks");
        keysConverter.put(com.biznessapps.layout.R.string.almost_there, "Almost there...");
        keysConverter.put(com.biznessapps.layout.R.string.amount_label, "Check Total");
        keysConverter.put(com.biznessapps.layout.R.string.anonymous_user, "Anonymous Android user");
        keysConverter.put(com.biznessapps.layout.R.string.anonymous_ios_user, "Anonymous iOS user");
        keysConverter.put(com.biznessapps.layout.R.string.app_not_being_maintained, "This app is no longer being maintained due to non-payment on behalf of the business.");
        keysConverter.put(com.biznessapps.layout.R.string.app_store, "App Store:");
        keysConverter.put(com.biznessapps.layout.R.string.artist, "Artist:");
        keysConverter.put(com.biznessapps.layout.R.string.attend, "Attend");
        keysConverter.put(com.biznessapps.layout.R.string.authentication, "Authenticating...");
        keysConverter.put(com.biznessapps.layout.R.string.author, "Author");
        keysConverter.put(com.biznessapps.layout.R.string.blocked_day, "We're not opened on this day.");
        keysConverter.put(com.biznessapps.layout.R.string.book_it, "Book It");
        keysConverter.put(com.biznessapps.layout.R.string.booking_successful, "Booking was done successfully");
        keysConverter.put(com.biznessapps.layout.R.string.branch_call_title, "Which location would you like to call?");
        keysConverter.put(com.biznessapps.layout.R.string.branch_directions_title, "Which location would you like directions to?");
        keysConverter.put(com.biznessapps.layout.R.string.calculate, "Calculate");
        keysConverter.put(com.biznessapps.layout.R.string.calendar_friday, "Friday");
        keysConverter.put(com.biznessapps.layout.R.string.calendar_monday, "Monday");
        keysConverter.put(com.biznessapps.layout.R.string.calendar_saturday, "Saturday");
        keysConverter.put(com.biznessapps.layout.R.string.calendar_sunday, "Sunday");
        keysConverter.put(com.biznessapps.layout.R.string.calendar_thursday, "Thursday");
        keysConverter.put(com.biznessapps.layout.R.string.calendar_tuesday, "Tuesday");
        keysConverter.put(com.biznessapps.layout.R.string.calendar_wednesday, "Wednesday");
        keysConverter.put(com.biznessapps.layout.R.string.call_number_request, "Do you want to call this number?");
        keysConverter.put(com.biznessapps.layout.R.string.call_us, "Call Us");
        keysConverter.put(com.biznessapps.layout.R.string.cancel, "Cancel");
        keysConverter.put(com.biznessapps.layout.R.string.cancel_reservation, "Cancel Reservation");
        keysConverter.put(com.biznessapps.layout.R.string.cancel_reservation_question, "Are you sure you want to cancel this reservation?");
        keysConverter.put(com.biznessapps.layout.R.string.cancelled, "Cancelled");
        keysConverter.put(com.biznessapps.layout.R.string.car_finder_email_message, "Please click on the link below to find out where I am.");
        keysConverter.put(com.biznessapps.layout.R.string.car_location, "Current Location");
        keysConverter.put(com.biznessapps.layout.R.string.cash, "CASH");
        keysConverter.put(com.biznessapps.layout.R.string.close, "Close");
        keysConverter.put(com.biznessapps.layout.R.string.closed_now, "Closed Now");
        keysConverter.put(com.biznessapps.layout.R.string.check_total, "Check Total");
        keysConverter.put(com.biznessapps.layout.R.string.checkin, "Check In");
        keysConverter.put(com.biznessapps.layout.R.string.checkin_hours_left, "hour(s) left");
        keysConverter.put(com.biznessapps.layout.R.string.checkin_interval, "You need to wait before you can check in again. Check-in interval is %d hours");
        keysConverter.put(com.biznessapps.layout.R.string.checkin_mins_left, "min(s) left");
        keysConverter.put(com.biznessapps.layout.R.string.checkin_scan_message, "You need to scan another %d times before you can use this coupon");
        keysConverter.put(com.biznessapps.layout.R.string.checking_unsuccess, "You need to get closer to the location marked");
        keysConverter.put(com.biznessapps.layout.R.string.choose_login_account, "Choose Login Account");
        keysConverter.put(com.biznessapps.layout.R.string.choose_photo, "Choose Photo");
        keysConverter.put(com.biznessapps.layout.R.string.choose_player_to_send_email, "Choose player to send email scorecard.");
        keysConverter.put(com.biznessapps.layout.R.string.chose_from_library, "Choose from Library");
        keysConverter.put(com.biznessapps.layout.R.string.collect_email_title, "Enter Your Email");
        keysConverter.put(com.biznessapps.layout.R.string.collect_stamps_for_coupon, "Collect %d more stamps to unlock this coupon.");
        keysConverter.put(com.biznessapps.layout.R.string.comment_hint, "Type your comment here...");
        keysConverter.put(com.biznessapps.layout.R.string.commenting_not_allowed, "Commenting is not allowed for this YouTube video.");
        keysConverter.put(com.biznessapps.layout.R.string.comments, "Comments");
        keysConverter.put(com.biznessapps.layout.R.string.completed_checkin, "%s completed %d%s check-in.");
        keysConverter.put(com.biznessapps.layout.R.string.completed_scans, "%s completed %d%s scan.");
        keysConverter.put(com.biznessapps.layout.R.string.completed_stamp, "%s completed %d%s stamp.");
        keysConverter.put(com.biznessapps.layout.R.string.completed_v2_stamp, "%s completed a stamp. Now at %d %s.");
        keysConverter.put(com.biznessapps.layout.R.string.redeemed_perk, "%s redeemed %s perk. %d %s remaining.");
        keysConverter.put(com.biznessapps.layout.R.string.confirm, "Confirm");
        keysConverter.put(com.biznessapps.layout.R.string.congratulations, "Congratulations!");
        keysConverter.put(com.biznessapps.layout.R.string.connect, "Connect");
        keysConverter.put(com.biznessapps.layout.R.string.connected_to_network, "Connected to %s");
        keysConverter.put(com.biznessapps.layout.R.string.contact, "Contact");
        keysConverter.put(com.biznessapps.layout.R.string.country, "Country");
        keysConverter.put(com.biznessapps.layout.R.string.coupon_cant_be_used, "This coupon cannot be used again.");
        keysConverter.put(com.biznessapps.layout.R.string.coupon_redeemed, "Coupon successfully redeemed");
        keysConverter.put(com.biznessapps.layout.R.string.coupon_state_1st, "st");
        keysConverter.put(com.biznessapps.layout.R.string.coupon_state_2nd, "nd");
        keysConverter.put(com.biznessapps.layout.R.string.coupon_state_3rd, "rd");
        keysConverter.put(com.biznessapps.layout.R.string.coupon_state_4th, "th");
        keysConverter.put(com.biznessapps.layout.R.string.coupons_checkin_n_times, "You need to check in another %d times before you can use this coupon");
        keysConverter.put(com.biznessapps.layout.R.string.coupons_scan_n_times, "Please scan another %d times to unlock a coupon");
        keysConverter.put(com.biznessapps.layout.R.string.course, "Course");
        keysConverter.put(com.biznessapps.layout.R.string.create_account, "Create Account");
        keysConverter.put(com.biznessapps.layout.R.string.current_game, "Current Game");
        keysConverter.put(com.biznessapps.layout.R.string.current_location, "Current Location");
        keysConverter.put(com.biznessapps.layout.R.string.dashboard, "Dashboard");
        keysConverter.put(com.biznessapps.layout.R.string.date, "Date");
        keysConverter.put(com.biznessapps.layout.R.string.days_template, "day(s) ago");
        keysConverter.put(com.biznessapps.layout.R.string.delete, "Delete");
        keysConverter.put(com.biznessapps.layout.R.string.delete_note, "Do you want to delete this note?");
        keysConverter.put(com.biznessapps.layout.R.string.demo_title, "Enter the code you have been given below to view a demo");
        keysConverter.put(com.biznessapps.layout.R.string.demo, "Demo");
        keysConverter.put(com.biznessapps.layout.R.string.description, "Description");
        keysConverter.put(com.biznessapps.layout.R.string.directions, "Directions");
        keysConverter.put(com.biznessapps.layout.R.string.disclaimer_label, "These figures are only a guide. We recommend that you obtain exact figures from a specific lender before committing to any loan.");
        keysConverter.put(com.biznessapps.layout.R.string.dismiss, "Dismiss");
        keysConverter.put(com.biznessapps.layout.R.string.done, "Done");
        keysConverter.put(com.biznessapps.layout.R.string.each_month_payment, "Your monthly repayment will be:");
        keysConverter.put(com.biznessapps.layout.R.string.edit_player, "Edit Player");
        keysConverter.put(com.biznessapps.layout.R.string.email, "Email");
        keysConverter.put(com.biznessapps.layout.R.string.email_is_not_correct, "Please verify your email is correct.");
        keysConverter.put(com.biznessapps.layout.R.string.email_login_title, "Enter Your Email");
        keysConverter.put(com.biznessapps.layout.R.string.email_login_description, "Input valid email");
        keysConverter.put(com.biznessapps.layout.R.string.email_photo_title, "Send Us a Photo");
        keysConverter.put(com.biznessapps.layout.R.string.email_results, "Email Results");
        keysConverter.put(com.biznessapps.layout.R.string.email_receipt, "Email Receipt");
        keysConverter.put(com.biznessapps.layout.R.string.error, "Error");
        keysConverter.put(com.biznessapps.layout.R.string.error_occured, "An error occurred.");
        keysConverter.put(com.biznessapps.layout.R.string.facebook, "Facebook");
        keysConverter.put(com.biznessapps.layout.R.string.failure, "Failure");
        keysConverter.put(com.biznessapps.layout.R.string.fan_wall_posts, "Fan Wall Posts");
        keysConverter.put(com.biznessapps.layout.R.string.featured, "Featured");
        keysConverter.put(com.biznessapps.layout.R.string.female, "Female");
        keysConverter.put(com.biznessapps.layout.R.string.fill_app_code, "Whoops! You have entered an invalid app code.  Please try again.");
        keysConverter.put(com.biznessapps.layout.R.string.fill_required_fields_message, "Please fill out the required fields");
        keysConverter.put(com.biznessapps.layout.R.string.find_qr_code, "Find a QR code");
        keysConverter.put(com.biznessapps.layout.R.string.finish, "Finish");
        keysConverter.put(com.biznessapps.layout.R.string.first_name, "First Name");
        keysConverter.put(com.biznessapps.layout.R.string.forgot, "Forgot");
        keysConverter.put(com.biznessapps.layout.R.string.forgot_your_password, "Forgot Your Password");
        keysConverter.put(com.biznessapps.layout.R.string.fo_add, "Add");
        keysConverter.put(com.biznessapps.layout.R.string.fo_add_item_to_order, "Add item to order!");
        keysConverter.put(com.biznessapps.layout.R.string.fo_address, "Address");
        keysConverter.put(com.biznessapps.layout.R.string.fo_apt, "Apt, Suite, Floor");
        keysConverter.put(com.biznessapps.layout.R.string.fo_asap, "ASAP");
        keysConverter.put(com.biznessapps.layout.R.string.fo_card, "CARD");
        keysConverter.put(com.biznessapps.layout.R.string.fo_card_payment_not_available, "Card payment is currently unavailable. Try again later.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_cart, "Cart");
        keysConverter.put(com.biznessapps.layout.R.string.fo_cart_updated, "Your cart has been updated");
        keysConverter.put(com.biznessapps.layout.R.string.fo_cart_is_empty, "Your cart is empty.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_categories, "Categories");
        keysConverter.put(com.biznessapps.layout.R.string.fo_checkout, "Check out");
        keysConverter.put(com.biznessapps.layout.R.string.fo_choose_items, "Choose Items");
        keysConverter.put(com.biznessapps.layout.R.string.fo_convenience_fee, "Convenience Fee");
        keysConverter.put(com.biznessapps.layout.R.string.fo_confirmation, "Confirmation");
        keysConverter.put(com.biznessapps.layout.R.string.fo_date, "Date");
        keysConverter.put(com.biznessapps.layout.R.string.fo_details, "Details");
        keysConverter.put(com.biznessapps.layout.R.string.fo_delivery, "Delivery");
        keysConverter.put(com.biznessapps.layout.R.string.fo_delivery_address_alert, "Cannot deliver to this address");
        keysConverter.put(com.biznessapps.layout.R.string.fo_delivery_fee, "Delivery Fee");
        keysConverter.put(com.biznessapps.layout.R.string.fo_delivery_minimum_alert, "Minimum order for delivery is");
        keysConverter.put(com.biznessapps.layout.R.string.fo_dine_in, "Dine-in");
        keysConverter.put(com.biznessapps.layout.R.string.fo_quantity, "Quantity");
        keysConverter.put(com.biznessapps.layout.R.string.fo_quantity_message, "How many do you want?");
        keysConverter.put(com.biznessapps.layout.R.string.fo_items_for, "Items for");
        keysConverter.put(com.biznessapps.layout.R.string.fo_item_price, "Item Price");
        keysConverter.put(com.biznessapps.layout.R.string.fo_locations, "Locations");
        keysConverter.put(com.biznessapps.layout.R.string.fo_location_nickname, "Location Nickname");
        keysConverter.put(com.biznessapps.layout.R.string.fo_location_nick_exists, "The location name already exists");
        keysConverter.put(com.biznessapps.layout.R.string.fo_location_enter_address, "Enter your address");
        keysConverter.put(com.biznessapps.layout.R.string.fo_location_warning, "If you leave this location your cart will be erased. Will you proceed anyway?");
        keysConverter.put(com.biznessapps.layout.R.string.fo_my_addresses, "My Addresses");
        keysConverter.put(com.biznessapps.layout.R.string.fo_no_availability_for_day_time, "No availability for selected day or time");
        keysConverter.put(com.biznessapps.layout.R.string.fo_no_availability_for_time, "No availability for selected service at this time");
        keysConverter.put(com.biznessapps.layout.R.string.fo_no_available_items, "Items in this order are not available at this time.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_one_or_more_no_available_items, "One or more items in your order will not be added to cart.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_no_available_service, "No available service(s) at this time");
        keysConverter.put(com.biznessapps.layout.R.string.fo_selected_items_not_available, "Items you have already selected are unavailable at this time.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_no_service_options_available, "No Service options are available.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_options, "Options");
        keysConverter.put(com.biznessapps.layout.R.string.fo_order_info, "Your order will be ready at %s");
        keysConverter.put(com.biznessapps.layout.R.string.fo_order_more, "Order More");
        keysConverter.put(com.biznessapps.layout.R.string.fo_past_orders, "Past Orders");
        keysConverter.put(com.biznessapps.layout.R.string.fo_payment, "Payment");
        keysConverter.put(com.biznessapps.layout.R.string.fo_payment_not_available, "No payment options are available");
        keysConverter.put(com.biznessapps.layout.R.string.fo_place_order, "Place Order");
        keysConverter.put(com.biznessapps.layout.R.string.fo_remove_cart_message, "Are you sure you want to remove this item from cart?");
        keysConverter.put(com.biznessapps.layout.R.string.fo_reorder, "Reorder");
        keysConverter.put(com.biznessapps.layout.R.string.fo_reorder_text1, "Selecting reorder will add items to your cart that are available at the selected time of checkout.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_reorder_text2, "Your previous special notes will also be used with this order.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_search_by_location, "Search by location");
        keysConverter.put(com.biznessapps.layout.R.string.fo_select_this_location, "Select this location");
        keysConverter.put(com.biznessapps.layout.R.string.fo_size, "Size");
        keysConverter.put(com.biznessapps.layout.R.string.fo_specific_instructions, "Specific instructions");
        keysConverter.put(com.biznessapps.layout.R.string.fo_select_day_time, "Please select day and time.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_select_order_type, "Please select order type.");
        keysConverter.put(com.biznessapps.layout.R.string.fo_takeout, "Takeout");
        keysConverter.put(com.biznessapps.layout.R.string.fo_tip, "Tip");
        keysConverter.put(com.biznessapps.layout.R.string.fo_today, "Today");
        keysConverter.put(com.biznessapps.layout.R.string.fo_total_charges, "Total Charges");
        keysConverter.put(com.biznessapps.layout.R.string.gallery_title, "Gallery");
        keysConverter.put(com.biznessapps.layout.R.string.gender, "Gender");
        keysConverter.put(com.biznessapps.layout.R.string.go, "Go");
        keysConverter.put(com.biznessapps.layout.R.string.go_back, "Go Back");
        keysConverter.put(com.biznessapps.layout.R.string.golf_course, "Golf Course");
        keysConverter.put(com.biznessapps.layout.R.string.golf_leave_game, "Are you sure to leave current game?Current game will be saved anyway.");
        keysConverter.put(com.biznessapps.layout.R.string.google_plus, "Google+");
        keysConverter.put(com.biznessapps.layout.R.string.google_store, "Play Store:");
        keysConverter.put(com.biznessapps.layout.R.string.gps, "GPS");
        keysConverter.put(com.biznessapps.layout.R.string.gps_disabled_info, "Location Services Disabled");
        keysConverter.put(com.biznessapps.layout.R.string.green_back, "Green Back");
        keysConverter.put(com.biznessapps.layout.R.string.green_front, "Green Front");
        keysConverter.put(com.biznessapps.layout.R.string.green_middle, "Green Middle");
        keysConverter.put(com.biznessapps.layout.R.string.handicap, "Handicap");
        keysConverter.put(com.biznessapps.layout.R.string.have_unlocked_coupon, "You have unlocked a new coupon!");
        keysConverter.put(com.biznessapps.layout.R.string.help, "Help");
        keysConverter.put(com.biznessapps.layout.R.string.history, "History");
        keysConverter.put(com.biznessapps.layout.R.string.hole, "Hole");
        keysConverter.put(com.biznessapps.layout.R.string.holes_colon, "Holes");
        keysConverter.put(com.biznessapps.layout.R.string.hours, "hours");
        keysConverter.put(com.biznessapps.layout.R.string.hours_template, "hr(s) ago");
        keysConverter.put(com.biznessapps.layout.R.string.html5_store, "HTML5:");
        keysConverter.put(com.biznessapps.layout.R.string.hyb, "Hyb.");
        keysConverter.put(com.biznessapps.layout.R.string.i_am_going, "I'm Going");
        keysConverter.put(com.biznessapps.layout.R.string.i_went, "I Went");
        keysConverter.put(com.biznessapps.layout.R.string.in, "   In   ");
        keysConverter.put(com.biznessapps.layout.R.string.info, "Info");
        keysConverter.put(com.biznessapps.layout.R.string.info_tier_link_message, "Can not see the above content correctly? Click here");
        keysConverter.put(com.biznessapps.layout.R.string.interest_rate, "Interest rate:");
        keysConverter.put(com.biznessapps.layout.R.string.join, "Join");
        keysConverter.put(com.biznessapps.layout.R.string.keep_coming_back, "Keep Coming Back");
        keysConverter.put(com.biznessapps.layout.R.string.last_name, "Last Name");
        keysConverter.put(com.biznessapps.layout.R.string.list, "List");
        keysConverter.put(com.biznessapps.layout.R.string.listed_by, "ListedBy");
        keysConverter.put(com.biznessapps.layout.R.string.live, "Live");
        keysConverter.put(com.biznessapps.layout.R.string.load_demo, "Load Demo");
        keysConverter.put(com.biznessapps.layout.R.string.load_more, "Load More");
        keysConverter.put(com.biznessapps.layout.R.string.loading, "Loading data... please wait");
        keysConverter.put(com.biznessapps.layout.R.string.loan_amount, "Loan amount:");
        keysConverter.put(com.biznessapps.layout.R.string.loan_term, "Loan term:");
        keysConverter.put(com.biznessapps.layout.R.string.location_absent, "Could not determine your current location.");
        keysConverter.put(com.biznessapps.layout.R.string.location_not_defined, "Sorry, I don't have your current location so I can't show you directions");
        keysConverter.put(com.biznessapps.layout.R.string.location_service_disabled, "Location Services Disabled");
        keysConverter.put(com.biznessapps.layout.R.string.location_is_not_available, "This location is currently unavailable.");
        keysConverter.put(com.biznessapps.layout.R.string.location_missed_alert, "Please select a location.");
        keysConverter.put(com.biznessapps.layout.R.string.location_title, "Location");
        keysConverter.put(com.biznessapps.layout.R.string.login, "Log In");
        keysConverter.put(com.biznessapps.layout.R.string.login_again, "Please log in again.");
        keysConverter.put(com.biznessapps.layout.R.string.login_completed, "Logged in");
        keysConverter.put(com.biznessapps.layout.R.string.logout, "Log out");
        keysConverter.put(com.biznessapps.layout.R.string.logout_message, "Are you sure you would like to log out from the selected network?");
        keysConverter.put(com.biznessapps.layout.R.string.loyalty_congrats_message, "Congratulations! You can now get one");
        keysConverter.put(com.biznessapps.layout.R.string.loyalty_stamp_dialog_message, "Please hand your device to the business representative who will stamp your card.");
        keysConverter.put(com.biznessapps.layout.R.string.loyalty_redeem_dialog_message, "Please hand your device to the business representative who will redeem your card.");
        keysConverter.put(com.biznessapps.layout.R.string.loyalty_dialog_title, "SECRET CODE");
        keysConverter.put(com.biznessapps.layout.R.string.loyalty_login_notice, "You need to login via social media or email address in order to use this feature.");
        keysConverter.put(com.biznessapps.layout.R.string.loyalty_dialog_yes_title, "Stamp");
        keysConverter.put(com.biznessapps.layout.R.string.loyalty_wrong_code_message, "Secret code is wrong");
        keysConverter.put(com.biznessapps.layout.R.string.mailing_list, "Mailing List");
        keysConverter.put(com.biznessapps.layout.R.string.mailing_list_add_success, "You have been added to our mailing list.");
        keysConverter.put(com.biznessapps.layout.R.string.mailing_list_question, "Would you like to join our mailing list?");
        keysConverter.put(com.biznessapps.layout.R.string.mailing_list_user_birthday_hint, "Birthday");
        keysConverter.put(com.biznessapps.layout.R.string.mailing_list_user_country_hint, "Country");
        keysConverter.put(com.biznessapps.layout.R.string.mailing_list_user_email_hint, "Email (Required)");
        keysConverter.put(com.biznessapps.layout.R.string.mailing_list_user_name_hint, "Name (Required)");
        keysConverter.put(com.biznessapps.layout.R.string.male, "Male");
        keysConverter.put(com.biznessapps.layout.R.string.main_menu, "Main Menu");
        keysConverter.put(com.biznessapps.layout.R.string.map, "Map");
        keysConverter.put(com.biznessapps.layout.R.string.message_all_type, "All");
        keysConverter.put(com.biznessapps.layout.R.string.message_image_type, "Offers");
        keysConverter.put(com.biznessapps.layout.R.string.message_tab_content_type, "Tab");
        keysConverter.put(com.biznessapps.layout.R.string.message_web_type, "Web URL");
        keysConverter.put(com.biznessapps.layout.R.string.messages, "Messages");
        keysConverter.put(com.biznessapps.layout.R.string.min, "min");
        keysConverter.put(com.biznessapps.layout.R.string.mins, "mins");
        keysConverter.put(com.biznessapps.layout.R.string.mins_template, "min(s) ago");
        keysConverter.put(com.biznessapps.layout.R.string.months_template, "month(s) ago");
        keysConverter.put(com.biznessapps.layout.R.string.music_tab_label, "Music");
        keysConverter.put(com.biznessapps.layout.R.string.my_comments, "My Comments");
        keysConverter.put(com.biznessapps.layout.R.string.more, "More");
        keysConverter.put(com.biznessapps.layout.R.string.n_a, "N/A");
        keysConverter.put(com.biznessapps.layout.R.string.n_feet_from_location, "%.2f feet from location");
        keysConverter.put(com.biznessapps.layout.R.string.n_miles_from_location, "%.2f miles from location");
        keysConverter.put(com.biznessapps.layout.R.string.name, "Name");
        keysConverter.put(com.biznessapps.layout.R.string.near_by, "Near By");
        keysConverter.put(com.biznessapps.layout.R.string.net_total, "Net Total");
        keysConverter.put(com.biznessapps.layout.R.string.network_error, "Network connection is required here");
        keysConverter.put(com.biznessapps.layout.R.string.new_game, "New Game");
        keysConverter.put(com.biznessapps.layout.R.string.new_player, "New Player");
        keysConverter.put(com.biznessapps.layout.R.string.news, "News");
        keysConverter.put(com.biznessapps.layout.R.string.next, "Next");
        keysConverter.put(com.biznessapps.layout.R.string.no, "No");
        keysConverter.put(com.biznessapps.layout.R.string.no_additional_info, "No additional information");
        keysConverter.put(com.biznessapps.layout.R.string.no_messages, "No Messages");
        keysConverter.put(com.biznessapps.layout.R.string.none, "None");
        keysConverter.put(com.biznessapps.layout.R.string.not_available, "Not Available");
        keysConverter.put(com.biznessapps.layout.R.string.notes, "Notes");
        keysConverter.put(com.biznessapps.layout.R.string.nothing_email, "This player has not email to send.");
        keysConverter.put(com.biznessapps.layout.R.string.nothing_found, "Nothing found");
        keysConverter.put(com.biznessapps.layout.R.string.number_incorrect_format_message, "You entered incorrect number(s)");
        keysConverter.put(com.biznessapps.layout.R.string.offline_caching_dialog_message, "Would you like to download content to view offline?");
        keysConverter.put(com.biznessapps.layout.R.string.offline_caching_dialog_title, "Offline Caching");
        keysConverter.put(com.biznessapps.layout.R.string.ok, "OK");
        keysConverter.put(com.biznessapps.layout.R.string.okay, "Okay");
        keysConverter.put(com.biznessapps.layout.R.string.okay_i_got_it, "Ok, I got it");
        keysConverter.put(com.biznessapps.layout.R.string.ongoing, "Ongoing");
        keysConverter.put(com.biznessapps.layout.R.string.open_now, "Open Now");
        keysConverter.put(com.biznessapps.layout.R.string.opening_hours, "Opening Hours");
        keysConverter.put(com.biznessapps.layout.R.string.optional, "Optional");
        keysConverter.put(com.biznessapps.layout.R.string.out, "   Out   ");
        keysConverter.put(com.biznessapps.layout.R.string.overview, "Overview");
        keysConverter.put(com.biznessapps.layout.R.string.par, "Par");
        keysConverter.put(com.biznessapps.layout.R.string.pars, "Pars");
        keysConverter.put(com.biznessapps.layout.R.string.password, "Password");
        keysConverter.put(com.biznessapps.layout.R.string.password_does_not_match, "Password does not match");
        keysConverter.put(com.biznessapps.layout.R.string.past_events, "Past");
        keysConverter.put(com.biznessapps.layout.R.string.payment_disabled, "This payment method is disabled for this service.");
        keysConverter.put(com.biznessapps.layout.R.string.payment_method, "Payment Method");
        keysConverter.put(com.biznessapps.layout.R.string.paypal, "Paypal");
        keysConverter.put(com.biznessapps.layout.R.string.people_going, "%s Going");
        keysConverter.put(com.biznessapps.layout.R.string.people_label, "Number of People");
        keysConverter.put(com.biznessapps.layout.R.string.people_went, "%s Went");
        keysConverter.put(com.biznessapps.layout.R.string.phone, "Phone");
        keysConverter.put(com.biznessapps.layout.R.string.phone_call_not_available, "Phone call is not available.");
        keysConverter.put(com.biznessapps.layout.R.string.phone_number, "Phone Number");
        keysConverter.put(com.biznessapps.layout.R.string.photo_saved, "Image is stored in Photo gallery");
        keysConverter.put(com.biznessapps.layout.R.string.photo_sharing, "I just looked at this photo at %s using their mobile app. Check it out! %s");
        keysConverter.put(com.biznessapps.layout.R.string.photo_upload, "Photo Upload");
        keysConverter.put(com.biznessapps.layout.R.string.photos, "Photos");
        keysConverter.put(com.biznessapps.layout.R.string.picture_sharing, "I just took this picture. Check it out.");
        keysConverter.put(com.biznessapps.layout.R.string.played_date, "Played Date");
        keysConverter.put(com.biznessapps.layout.R.string.player, "Player");
        keysConverter.put(com.biznessapps.layout.R.string.player_name, "Player Name");
        keysConverter.put(com.biznessapps.layout.R.string.players, "Players");
        keysConverter.put(com.biznessapps.layout.R.string.please_enter_valid_name, "Please enter valid name");
        keysConverter.put(com.biznessapps.layout.R.string.please_select_course, "Please select a golf course.");
        keysConverter.put(com.biznessapps.layout.R.string.please_select_gender, "Please select gender");
        keysConverter.put(com.biznessapps.layout.R.string.please_select_handicap, "Please select handicap");
        keysConverter.put(com.biznessapps.layout.R.string.please_select_tee, "Please select tee");
        keysConverter.put(com.biznessapps.layout.R.string.popular, "Popular");
        keysConverter.put(com.biznessapps.layout.R.string.post, "Post");
        keysConverter.put(com.biznessapps.layout.R.string.post_activity, "Post Activity?");
        keysConverter.put(com.biznessapps.layout.R.string.post_comment, "Post Comment");
        keysConverter.put(com.biznessapps.layout.R.string.posted, "Posted");
        keysConverter.put(com.biznessapps.layout.R.string.posted_date, "Posted Date");
        keysConverter.put(com.biznessapps.layout.R.string.pre_payment_label, "Pre-Payment:");
        keysConverter.put(com.biznessapps.layout.R.string.price, "Price:");
        keysConverter.put(com.biznessapps.layout.R.string.property, "Property");
        keysConverter.put(com.biznessapps.layout.R.string.provide_email, "Please provide your email address");
        keysConverter.put(com.biznessapps.layout.R.string.pull_to_refresh, "Pull to Refresh");
        keysConverter.put(com.biznessapps.layout.R.string.putts, "Putts");
        keysConverter.put(com.biznessapps.layout.R.string.putts_caps, "Putts");
        keysConverter.put(com.biznessapps.layout.R.string.qr_unsuccess_scanning, "Nothing matched that QR Code");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_agent, "Agent:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_appliances, "Appliances");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_architectural_style, "Achitectural Style");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_asphalt, "Asphalt");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_attic, "Attic");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_balcony_patio, "Balcony/patio");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_barbecue_area, "Barbecue area");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_baseboard, "Baseboard");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_basement, "Basement");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_basketball_court, "Basketball court");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_breakfast_nook, "Breakfast nook");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_brick, "Brick");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_building_amenities, "Building Amenities");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_built_up, "Built-up");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_bungalow, "Bungalow");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_cable_ready, "Cable ready");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_cape_cod, "Cape Cod");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_carpet, "Carpet");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_carport, "Carport");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_category_own, "Own");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_category_rentals, "Rentals");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_ceiling_fans, "Ceiling fans");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_cement_concrete, "Cement / Concrete");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_central, "Central");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_city, "City");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_coal, "Coal");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_colonial, "Colonial");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_composition, "Composition");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_concrete, "Concrete");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_contemporary, "Contemporary");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_controlled_access, "Controlled access");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_cooling_type, "Cooling Type");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_craftsman, "Craftsman");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_deck, "Deck");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_dining_room, "Dining room");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_disabled_access, "Disabled access");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_dishwasher, "Dishwasher");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_dock, "Dock");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_doorman, "Doorman");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_double_pane_storm_windows, "Double pane/storm windows");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_dryer, "Dryer");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_electric, "Electric");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_elevator, "Elevator");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_email, "Email:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_evaporative, "Evaporative");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_exterior, "Exterior");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_family_room, "Family room");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_fenced_yard, "Fenced yard");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_finished, "Finished");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_fireplace, "Fireplace");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_fitness_center, "Fitness center");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_floor_covering, "Floor Covering");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_forced_air, "Forced air");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_freezer, "Freezer");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_frenhc, "French");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_garage_attached, "Garage - Attached");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_garage_detached, "Garage - Detached");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_garbage_disposal, "Garbage disposal");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_garden, "Garden");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_gas, "Gas");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_gated_entry, "Gated entry");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_georgian, "Georgian");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_geothermal, "Geothermal");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_greenhouse, "Greenhouse");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_hardwood, "Hardwood");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_heat_pump, "Heat pump");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_heating_fuel, "Heating Fuel");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_heating_type, "Heating Type");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_hot_tub_spa, "Hot tub/spa");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_indoor_features, "Indoor Features");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_intercom_system, "Intercom system");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_jetted_tub, "Jetted tub");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_laminate, "Laminate");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_laundry_room, "Laundry room");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_lawn, "Lawn");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_library, "Library");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_linoleum_vinyl, "Linoleum / Vinyl");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_loft, "Loft");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_lot_size, "Lot Size:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_lotunit_acres, "Acres");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_lotunit_sqft, "Sq ft");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_lotunit_meters, "Meters");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_master_bath, "Master bath");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_metal, "Metal");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_microwave, "Microwave");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_mil_apartment, "Mother-in-law apartment");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_modern, "Modern");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_mountain, "Mountain");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_mud_room, "Mud room");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_near_transportation, "Near transportation");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_none, "None");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_off_street, "Off-street");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_office, "Office");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_oil, "Oil");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_on_street, "On-street");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_other, "Other");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_outdoor_amenities, "Outdoor Amenities");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_pactially_finished, "Partially finished");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_pantry, "Pantry");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_park, "Park");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_parking, "Parking");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_phone, "Phone:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_pond, "Pond");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_pool, "Pool");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_porch, "Porch");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_propane_butane, "Propane / Butane");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_property_size, "Property Size:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_queen_anne_victorian, "Queen Anne / Victorian");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_radiant, "Radiant");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_ranch_rambler, "Ranch / Rambler");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_range_oven, "Range / Oven");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_recreation_room, "Recreation room");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_refrigeration, "Refrigeration");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_refrigerator, "Refrigerator");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_roof, "Roof");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_rooms, "Rooms");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_rv_parking, "RV parking");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_sauna, "Sauna");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_security_system, "Security system");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_sfp_style, "Santa Fe / Pueblo Style");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_shake_shingle, "Shake / Shingle");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_shingle, "Shingle");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_skylights, "Skylights");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_slate, "Slate");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_softwood, "Softwood");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_solar, "Solar");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_solarium_atrium, "Solarium / Atrium");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_spanish, "Spanish");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_split_level, "Split-level");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_sport_court, "Sports court");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_sprinkler_system, "Sprinkler system");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_status, "Status:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_stone, "Stone");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_storage, "Storage");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_stove, "Stove");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_stucco, "Stucco");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_sun_room, "Sun room");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_tennis_court, "Tennis court");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_territorial, "Territorial");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_tile, "Tile");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_trash_compactor, "Trash compactor");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_tudor, "Tudor");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_type, "Type:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_unfinished, "Unfinished");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_vaulted_ceiling, "Vaulted ceiling");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_view, "View");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_vinyl, "Vinyl");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_walkin_closet, "Walk-in closet");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_wall, "Wall");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_washer, "Washer");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_water, "Water");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_waterfront, "Waterfront");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_wet_bar, "Wet bar");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_wired, "Wired");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_wood, "Wood");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_wood_pellet, "Wood / Pellet");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_wood_products, "Wood products");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_workshop, "Workshop");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_year_built, "Year Built:");
        keysConverter.put(com.biznessapps.layout.R.string.real_estate_year_updated, "Year Updated:");
        keysConverter.put(com.biznessapps.layout.R.string.recent, "Recent");
        keysConverter.put(com.biznessapps.layout.R.string.recent_photos, "Recent Photos");
        keysConverter.put(com.biznessapps.layout.R.string.recents, "Recents");
        keysConverter.put(com.biznessapps.layout.R.string.recordings, "%d Recordings, %s");
        keysConverter.put(com.biznessapps.layout.R.string.recover_password, "Recover Password");
        keysConverter.put(com.biznessapps.layout.R.string.recovery_email, "Please check the recovery email.");
        keysConverter.put(com.biznessapps.layout.R.string.recovery_failed, "Recovery failed.");
        keysConverter.put(com.biznessapps.layout.R.string.red, "Red");
        keysConverter.put(com.biznessapps.layout.R.string.redeem, "Redeem");
        keysConverter.put(com.biznessapps.layout.R.string.redeem_coupon, "Are you sure you want to redeem this coupon?");
        keysConverter.put(com.biznessapps.layout.R.string.redeem_loyalty_card, "Redeem to reuse this loyalty card.");
        keysConverter.put(com.biznessapps.layout.R.string.redeemed, "REDEEMED!");
        keysConverter.put(com.biznessapps.layout.R.string.redeemed_coupon, "%s redeemed this coupon");
        keysConverter.put(com.biznessapps.layout.R.string.redeemed_loyalty, "%s redeemed this loyalty.");
        keysConverter.put(com.biznessapps.layout.R.string.refreshing_data, "Refreshing data...");
        keysConverter.put(com.biznessapps.layout.R.string.register, "Register");
        keysConverter.put(com.biznessapps.layout.R.string.registration_failed, "Registration Failed");
        keysConverter.put(com.biznessapps.layout.R.string.registration_successful, "Registration Successful");
        keysConverter.put(com.biznessapps.layout.R.string.release_to_refresh, "Release to refresh");
        keysConverter.put(com.biznessapps.layout.R.string.replies, "Replies");
        keysConverter.put(com.biznessapps.layout.R.string.reply, "Reply");
        keysConverter.put(com.biznessapps.layout.R.string.required, "Required");
        keysConverter.put(com.biznessapps.layout.R.string.reseller_dashboard_login, "Do you wish to login using App Code? App Code:");
        keysConverter.put(com.biznessapps.layout.R.string.reseller_dashboard_logout, "Do you wish to logout of your dashboard?");
        keysConverter.put(com.biznessapps.layout.R.string.reseller_return_message, "Would you like to return to the dashboard?");
        keysConverter.put(com.biznessapps.layout.R.string.reseller_no_app_message, "Try checking out the demo app section.");
        keysConverter.put(com.biznessapps.layout.R.string.reseller_not_active_account, "Your Account Is Not Active, Please Contact Our Support");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_cancel_appt_message, "Failure to cancel the reservation.");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_failure, "Failure to make reservation.");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_max_service_limit, "This service is fully reserved for the selected time. Please select another time.");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_time_slot_filled, "This time slot has been filled.Please chose a different time.");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_has_passed, "The reservation was already past.");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_recover_failed, "Recovery failed.");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_register_account_title, "Register");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_update_profile_failed, "Update Failed");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_week_friday, "Friday");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_week_monday, "Monday");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_week_saturday, "Saturday");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_week_sunday, "Sunday");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_week_thursday, "Thursday");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_week_tuesday, "Tuesday");
        keysConverter.put(com.biznessapps.layout.R.string.reservation_week_wednesday, "Wednesday");
        keysConverter.put(com.biznessapps.layout.R.string.reset, "Reset");
        keysConverter.put(com.biznessapps.layout.R.string.reward_loyalty, "%s got reward of this loyalty.");
        keysConverter.put(com.biznessapps.layout.R.string.rewards, "Rewards");
        keysConverter.put(com.biznessapps.layout.R.string.right_now, "right now");
        keysConverter.put(com.biznessapps.layout.R.string.save, "Save");
        keysConverter.put(com.biznessapps.layout.R.string.save_to_album, "Save to Photo Album");
        keysConverter.put(com.biznessapps.layout.R.string.scan, "Scan!");
        keysConverter.put(com.biznessapps.layout.R.string.scan_code_description, "Scan the code with QR scanner and get linked directly to content or unlock hidden items.");
        keysConverter.put(com.biznessapps.layout.R.string.scan_qr, "SCAN A QR CODE");
        keysConverter.put(com.biznessapps.layout.R.string.scan_qr_steps1, "Find a QR code for this app.");
        keysConverter.put(com.biznessapps.layout.R.string.scan_qr_steps2, "Make sure you have good lighting.");
        keysConverter.put(com.biznessapps.layout.R.string.scan_qr_steps3, "Line up the camera view finder with the code.");
        keysConverter.put(com.biznessapps.layout.R.string.scan_qr_steps4, "Wait for the camera to detect the code.");
        keysConverter.put(com.biznessapps.layout.R.string.scan_qr_steps5, "The app will display the scanned code.");
        keysConverter.put(com.biznessapps.layout.R.string.scan_qr_title, "Scan QR");
        keysConverter.put(com.biznessapps.layout.R.string.schedule_appointment_button, "Schedule Reservation");
        keysConverter.put(com.biznessapps.layout.R.string.score, "Score");
        keysConverter.put(com.biznessapps.layout.R.string.score_card, "Scorecard");
        keysConverter.put(com.biznessapps.layout.R.string.sdcard_missed, "Sorry, but you don't have sdcard");
        keysConverter.put(com.biznessapps.layout.R.string.search, "Search");
        keysConverter.put(com.biznessapps.layout.R.string.secs_template, "sec(s) ago");
        keysConverter.put(com.biznessapps.layout.R.string.select_course, "Select a course");
        keysConverter.put(com.biznessapps.layout.R.string.select_golf, "Please select a golf course.");
        keysConverter.put(com.biznessapps.layout.R.string.select_players, "Select Players");
        keysConverter.put(com.biznessapps.layout.R.string.sending_tweet_failure, "Sorry, there was a problem posting to Twitter.  Please try again later.");
        keysConverter.put(com.biznessapps.layout.R.string.sending_tweet_successfully, "Successfully sent to Twitter");
        keysConverter.put(com.biznessapps.layout.R.string.server_connection_failure, "Please check your data connection");
        keysConverter.put(com.biznessapps.layout.R.string.service, "Service");
        keysConverter.put(com.biznessapps.layout.R.string.set, "Set");
        keysConverter.put(com.biznessapps.layout.R.string.set_timer, "Set Timer");
        keysConverter.put(com.biznessapps.layout.R.string.share, "Share");
        keysConverter.put(com.biznessapps.layout.R.string.share_by_email, "Share by Email");
        keysConverter.put(com.biznessapps.layout.R.string.share_by_sms, "Share by SMS");
        keysConverter.put(com.biznessapps.layout.R.string.share_image_url_with_app_description, "Hi, I just looked at %s inside %s, using their mobile app. Check it out! %s");
        keysConverter.put(com.biznessapps.layout.R.string.share_on_facebook, "Share on Facebook");
        keysConverter.put(com.biznessapps.layout.R.string.share_on_google_plus, "Share on Google+");
        keysConverter.put(com.biznessapps.layout.R.string.share_on_twitter, "Share on Twitter");
        keysConverter.put(com.biznessapps.layout.R.string.shares_number, "Shares");
        keysConverter.put(com.biznessapps.layout.R.string.sharing, "Sharing");
        keysConverter.put(com.biznessapps.layout.R.string.sharing_canceled, "Cancelled");
        keysConverter.put(com.biznessapps.layout.R.string.sharing_completed, "Completed");
        keysConverter.put(com.biznessapps.layout.R.string.skip, "Skip");
        keysConverter.put(com.biznessapps.layout.R.string.social_connect, "Social Connect");
        keysConverter.put(com.biznessapps.layout.R.string.social_networks_label, "Please log in with your social account for better experience with social features.");
        keysConverter.put(com.biznessapps.layout.R.string.something_went_wrong, "Something went wrong. Please try again later.");
        keysConverter.put(com.biznessapps.layout.R.string.songs, "%s songs");
        keysConverter.put(com.biznessapps.layout.R.string.sport_stats_clear_text, "Are you sure you'd like to reset?");
        keysConverter.put(com.biznessapps.layout.R.string.stamp, "Stamp");
        keysConverter.put(com.biznessapps.layout.R.string.stamp_card, "Stamp Card");
        keysConverter.put(com.biznessapps.layout.R.string.stay_here, "Stay Here");
        keysConverter.put(com.biznessapps.layout.R.string.stop_timer, "Stop Timer");
        keysConverter.put(com.biznessapps.layout.R.string.submit, "SUBMIT");
        keysConverter.put(com.biznessapps.layout.R.string.success, "Success");
        keysConverter.put(com.biznessapps.layout.R.string.successfully_posted, "Successfully posted");
        keysConverter.put(com.biznessapps.layout.R.string.successfully_saved, "Successfully saved");
        keysConverter.put(com.biznessapps.layout.R.string.take_photo, "Take a Photo");
        keysConverter.put(com.biznessapps.layout.R.string.tap_plus_button_new_golf_game, "Tap + button to add a new golf game.");
        keysConverter.put(com.biznessapps.layout.R.string.tap_plus_button_add_player, "Tap + button to add a player.");
        keysConverter.put(com.biznessapps.layout.R.string.tee, "Tee");
        keysConverter.put(com.biznessapps.layout.R.string.tees, "Tees");
        keysConverter.put(com.biznessapps.layout.R.string.time, "Time");
        keysConverter.put(com.biznessapps.layout.R.string.time_label, "Time:");
        keysConverter.put(com.biznessapps.layout.R.string.time_passed, "Time Passed");
        keysConverter.put(com.biznessapps.layout.R.string.tip_each_person_pay, "Each person pays");
        keysConverter.put(com.biznessapps.layout.R.string.tip_pay_label, "Tip each person pays");
        keysConverter.put(com.biznessapps.layout.R.string.tip_percent_label, "Tip Percentage");
        keysConverter.put(com.biznessapps.layout.R.string.title, "Title");
        keysConverter.put(com.biznessapps.layout.R.string.thank_you, "Thank you");
        keysConverter.put(com.biznessapps.layout.R.string.token_issue, "Token Issue");
        keysConverter.put(com.biznessapps.layout.R.string.total, "Total");
        keysConverter.put(com.biznessapps.layout.R.string.total_amount, "Total Amount");
        keysConverter.put(com.biznessapps.layout.R.string.total_tip, "Total Tip");
        keysConverter.put(com.biznessapps.layout.R.string.total_yards, "Total Yards");
        keysConverter.put(com.biznessapps.layout.R.string.twitter, "Twitter");
        keysConverter.put(com.biznessapps.layout.R.string.unknown_error, "Oops! An error occurred");
        keysConverter.put(com.biznessapps.layout.R.string.unlocked, "Unlocked!");
        keysConverter.put(com.biznessapps.layout.R.string.unlocked_coupon, "%s unlocked this coupon");
        keysConverter.put(com.biznessapps.layout.R.string.upcoming_events, "Upcoming");
        keysConverter.put(com.biznessapps.layout.R.string.update, "Update");
        keysConverter.put(com.biznessapps.layout.R.string.update_failed, "Update Failed");
        keysConverter.put(com.biznessapps.layout.R.string.update_status, "Update Status");
        keysConverter.put(com.biznessapps.layout.R.string.update_successful, "Update Successful");
        keysConverter.put(com.biznessapps.layout.R.string.upload, "Upload");
        keysConverter.put(com.biznessapps.layout.R.string.username, "Username");
        keysConverter.put(com.biznessapps.layout.R.string.view_website, "Website");
        keysConverter.put(com.biznessapps.layout.R.string.voice_recording, "Voice Recording");
        keysConverter.put(com.biznessapps.layout.R.string.voice_removing, "Do you want to delete this voice?");
        keysConverter.put(com.biznessapps.layout.R.string.voice_sharing, "I recorded a voice message. Check it out.");
        keysConverter.put(com.biznessapps.layout.R.string.weeks_template, "week(s) ago");
        keysConverter.put(com.biznessapps.layout.R.string.words_notepad_count, "%d words");
        keysConverter.put(com.biznessapps.layout.R.string.wrong_credentials, "Wrong user name or password");
        keysConverter.put(com.biznessapps.layout.R.string.wrong_email_or_password, "Email or Password is incorrect");
        keysConverter.put(com.biznessapps.layout.R.string.yards, "yards");
        keysConverter.put(com.biznessapps.layout.R.string.you_were_awarded_a_stamp_title, "Loyalty Awards");
        keysConverter.put(com.biznessapps.layout.R.string.you_were_awarded_a_stamp_description, "You were awarded a stamp for downloading the app");
        keysConverter.put(com.biznessapps.layout.R.string.loan_term_input_hint, "years");
        keysConverter.put(com.biznessapps.layout.R.string.years_template, "year(s) ago");
        keysConverter.put(com.biznessapps.layout.R.string.yes, "Yes");
        keysConverter.put(com.biznessapps.layout.R.string.zip, "Zip");
        keysConverter.put(com.biznessapps.layout.R.string.black, "Black");
        keysConverter.put(com.biznessapps.layout.R.string.blue, "Blue");
        keysConverter.put(com.biznessapps.layout.R.string.white, "White");
        keysConverter.put(com.biznessapps.layout.R.string.red, "Red");
        keysConverter.put(com.biznessapps.layout.R.string.green, "Green");
    }
}
