// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

// Referenced classes of package com.paypal.android.sdk:
//            k, cG

public final class A
    implements k
{

    private static final Map a = new HashMap();
    private static final Map b = new HashMap();
    private static final Map c = new HashMap();

    public A()
    {
        a.put(cG.a, "Godta og betal");
        a.put(cG.b, "og andre");
        a.put(cG.c, "Godkjenner");
        a.put(cG.d, "Tilbake");
        a.put(cG.e, "Reserve");
        a.put(cG.f, "Avbryt");
        a.put(cG.g, "American Express");
        a.put(cG.h, "Carta Aura");
        a.put(cG.i, "Carte Aurore");
        a.put(cG.j, "Carta Prepagata PayPal");
        a.put(cG.k, "Carte Bancaire");
        a.put(cG.l, "Cofinoga");
        a.put(cG.m, "Delta");
        a.put(cG.n, "Discover");
        a.put(cG.o, "Electron");
        a.put(cG.p, "JCB");
        a.put(cG.q, "Maestro");
        a.put(cG.r, "MasterCard");
        a.put(cG.s, "Postepay");
        a.put(cG.t, "4 \351toiles");
        a.put(cG.u, "Tarjeta Aurora");
        a.put(cG.v, "Visa");
        a.put(cG.w, "Endre betalingsmetode");
        a.put(cG.x, "Brukskonto");
        a.put(cG.y, "Kontrollerer denne enheten \u2026");
        a.put(cG.z, "Fjern kortopplysningene");
        a.put(cG.A, "Bekreft");
        a.put(cG.B, "Er du sikker p\345 at du vil fjerne kortopplysningene dine?");
        a.put(cG.C, "Belast kortet");
        a.put(cG.D, "Er du sikker p\345 at du vil logge av PayPal?");
        a.put(cG.E, "Betal");
        a.put(cG.F, "Godta");
        a.put(cG.G, "Opprettelsesdato for kontoen");
        a.put(cG.H, "Kontostatus");
        a.put(cG.I, "Kontotype");
        a.put(cG.J, "Adresse");
        a.put(cG.K, "Aldersgruppe");
        a.put(cG.L, "F\370dselsdato");
        a.put(cG.M, "E-postadresse");
        a.put(cG.N, "Fullt navn");
        a.put(cG.O, "Kj\370nn");
        a.put(cG.P, "Spr\345k");
        a.put(cG.Q, "Norsk, Norge");
        a.put(cG.R, "Telefon");
        a.put(cG.S, "Tidssone");
        a.put(cG.T, "Del f\370lgende: %s.");
        a.put(cG.U, "Bruk s\370ml\370s-kassen.");
        a.put(cG.V, "%s ber om at du:");
        a.put(cG.W, "Del <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        a.put(cG.X, "Aktiver visning av betalingskilder slik at du kan velge en.");
        a.put(cG.Y, "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\370p hos %2$s via PayPal. Du ber PayPal om \345 betale alle summer som %3$s ber om.");
        a.put(cG.Z, "Tillater at de legger til og administrerer et fordelskort i PayPal-lommeboken din.");
        a.put(cG.aa, "Godtar %1$s sine <a href='%2$s'>retningslinjer for personvern</a> og <a href='%3$s'>brukeravtale</a>.");
        a.put(cG.ab, "Gi vedkommende tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        a.put(cG.ac, "Gi vedkommende tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        a.put(cG.ad, "Godta");
        a.put(cG.ae, "E-postadresse");
        a.put(cG.af, "Eksempeldata");
        a.put(cG.ag, "Sandbox");
        a.put(cG.ah, "Utl\370per");
        a.put(cG.ai, "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingsmetodene dine som er tilgjengelige for bruk.</p>");
        a.put(cG.aj, "Har du glemt passordet?");
        a.put(cG.ak, "Fra");
        a.put(cG.al, "Hvordan vil du finansiere fremtidige betalinger til %1$s er?");
        a.put(cG.am, "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard betalingskilden din brukes til \345 utf\370re fremtidige PayPal-betalinger for denne forhandleren.</p><p>Hvis du vil avbryte denne avtalen, logger du p\345 PayPal-kontoen, g\345r til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For \345 kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten pr\370vetransaksjonen, men ingen penger overf\370res.</p>");
        a.put(cG.an, "Intern feil");
        a.put(cG.ao, "<p>Ved \345 klikke p\345 knappen nedenfor, godtar jeg vilk\345rene i <a href='%1$s'>PayPals brukeravtale</a> og jeg erkl\346rer samtidig at jeg overholder japanske lover og forskrifter, herunder sanksjonsbestemmelser om betalinger til Nord-Korea og Iran, i tr\345d med japansk <a href='%2$s'>lovgivning om handel med utenlandske produkter og valuta</a>, for \345 fullf\370re transaksjonen.</p>");
        a.put(cG.ap, "Logg p\345");
        a.put(cG.aq, "Logg p\345 med PayPal");
        a.put(cG.ar, "Logg ut");
        a.put(cG.as, "Logg ut");
        a.put(cG.at, "OK");
        a.put(cG.au, "Passord");
        a.put(cG.av, "Betal etter levering");
        a.put(cG.aw, "Betal med");
        a.put(cG.ax, "Betal med kort");
        a.put(cG.ay, "PayPal-saldo");
        a.put(cG.az, "PayPal Credit");
        a.put(cG.aA, "Telefonnummer");
        a.put(cG.aB, "PIN-kode");
        a.put(cG.aC, "Foretrukket betalingsmetode");
        a.put(cG.aD, "PayPal beskytter <a href='%s'>personvern</a>-opplysningene dine og den \370konomiske informasjonen din.");
        a.put(cG.aE, "Behandler");
        a.put(cG.aF, "Husk kortet");
        a.put(cG.aG, "Pengeforesp\370rsel");
        a.put(cG.aH, "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        a.put(cG.aI, "Sparekonto");
        a.put(cG.aJ, "Betal/overf\370r");
        a.put(cG.aK, "Det var et kommunikasjonsproblem med PayPal-serverne. Pr\370v p\345 nytt.");
        a.put(cG.aL, "Logg deg p\345 PayPal p\345 nytt.");
        a.put(cG.aM, "\330kten er utl\370pt");
        a.put(cG.aN, "Leveringsadresse");
        a.put(cG.aO, "Ny p\345 PayPal? Opprett konto");
        a.put(cG.aP, "Forbli p\345logget");
        a.put(cG.aQ, "Systemfeil (%s). Pr\370v p\345 nytt senere.");
        a.put(cG.aR, "Pr\370v p\345 nytt");
        a.put(cG.aS, "Kan ikke logge p\345, fordi p\345loggingen til kontoen din har godkjenning med to faktorer.");
        a.put(cG.aT, "Sikkerhetskode");
        a.put(cG.aU, "Send en tekstmelding til telefonen din. Den 6-sifrede koden du mottar, er gyldig i 5 minutter.");
        a.put(cG.aV, "Sender meldingen");
        a.put(cG.aW, "Oppgi den 6-sifrede sikkerhetskoden");
        a.put(cG.aX, "Ditt mobilnummer");
        a.put(cG.aY, "Send melding");
        a.put(cG.aZ, "Send meldingen p\345 nytt");
        a.put(cG.ba, "Kan ikke logge p\345, fordi p\345loggingen til kontoen din har godkjenning med to faktorer. G\345 til PayPals nettsted for \345 aktivere sikkerhetsn\370kkelen din.");
        a.put(cG.bb, "Betaling fra denne enheten er ikke tillatt.");
        a.put(cG.bc, "Uautorisert enhet");
        a.put(cG.bd, "Betalinger til denne forhandleren er ikke tillatt (ugyldig bruker-id).");
        a.put(cG.be, "Ugyldig forhandler");
        a.put(cG.bf, "Det oppsto et problem ved behandlingen av betalingen. Pr\370v p\345 nytt.");
        a.put(cG.bg, "Ukjent betalingsmetode");
        a.put(cG.bh, "Vi beklager");
        a.put(cG.bi, "Din bestilling");
        a.put(cG.bj, "Vil du fjerne kortet?");
        a.put(cG.bk, "Godkjenningen mislyktes");
        a.put(cG.bl, "Tilkobling mislykket");
        a.put(cG.bm, "P\345logging mislyktes");
        a.put(cG.bn, "Logg p\345 med passord");
        a.put(cG.bo, "Logg p\345 med PIN");
        a.put(cG.bp, "Et \370yeblikk \u2026");
        a.put(cG.bq, "Betaling mislyktes");
        a.put(cG.br, "Skann");
        a.put(cG.bs, "Feil sikkerhetskode. Pr\370v p\345 nytt.");
        a.put(cG.bt, "via");
        a.put(cG.bu, "Systemfeil. Pr\370v p\345 nytt senere.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Del informasjon om <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Del informasjon om <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Del informasjon om <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Del informasjon om <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Del informasjon med dem om <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Del <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Del <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Del informasjon om <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Del informasjon om <a href='%1$s'>betalingskildene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Del <a href='%1$s'>betalingskildene</a> p\345 vegne av deg inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\370p hos %2$s via PayPal. Du ber PayPal om \345 betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\370p hos %2$s via PayPal. Du ber PayPal om \345 betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\370p via PayPal. Du gir PayPal din godkjenning, og ber oss om \345 betale alle bel\370p.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\370p via PayPal. Du gir PayPal din godkjenning, og ber oss om \345 betale alle bel\370p.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\370p via PayPal. Du gir PayPal din godkjenning, og ber oss om \345 betale alle bel\370p.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Forh\345ndsgodkjenn fremtidige betalinger fra PayPal-kontoen din uten \345 logge p\345 PayPal hver gang. <a href='%1$s'>Se ytterligere vilk\345r</a>, inkludert betalingsmetoder og hvordan du kan avbryte fremtidige betalinger.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Gi %2$s tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Gi %2$s tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Gi %2$s tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Gi %2$s tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Gi %2$s tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Gi %2$s tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Gi %2$s tillatelse til \345 <a href='%1$s'>be om penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Gi %2$s tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Gi %2$s tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Gi %2$s tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Gi %2$s tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Gi %2$s tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Gi %2$s tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Gi %2$s tillatelse til \345 <a href='%1$s'>overf\370re penger</a> p\345 dine vegne inntil du trekker tilbake tillatelsen.");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingskildene dine som er tilgjengelige for bruk.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>Din standard betalingsmetode (PayPal-saldo, tilknyttet bankkonto eller betalingskort, i denne rekkef\370lgen) brukes til \345 betale for PayPal-kj\370p. V\346r oppmerksom p\345 at hvis den standard betalingsmetoden din ikke har nok penger til \345 dekke kj\370pet, kan banken eller kortleverand\370ren belaste deg et gebyr.</p><p>For \345 avbryte denne avtalen m\345 du logge p\345 PayPal-kontoen din og g\345 til <strong>Profil</strong>, s\345 klikker du p\345 <strong>Mine innstillinger</strong> og <strong>Endre</strong> ved siden av \u2018Logg p\345 med PayPal\u2019.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>PayPal-saldoen din eller det prim\346re betalingskortet ditt brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne avtalen, logger du p\345 PayPal-kontoen, g\345r til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>Betalingsmetoden du angir som standard brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne avtalen, logger du p\345 PayPal-kontoen, g\345r til <strong>Profil</strong> &gt; <strong>Innstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard betalingskilden din brukes til \345 utf\370re fremtidige PayPal-betalinger hos denne forhandleren.</p><p>Hvis du vil avslutte denne avtalen, logger du p\345 PayPal-kontoen din, g\345r til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For \345 kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten pr\370vetransaksjonen, men ingen penger overf\370res.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>Betalingsmetoden du angir som standard brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\345 PayPal-kontoen din, g\345r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\345ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>Betalingsmetoden du angir som standard brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\345 PayPal-kontoen din, g\345r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\345ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>PayPal-saldoen din eller det prim\346re betalingskortet ditt brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne avtalen, logger du p\345 PayPal-kontoen, g\345r til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>Betalingsmetoden du angir som standard brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\345 PayPal-kontoen din, g\345r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\345ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>Betalingsmetoden du angir som standard brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\345 PayPal-kontoen din, g\345r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\345ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\370vetransaksjon, men ingen penger overf\370res.</p><p>Betalingsmetoden du angir som standard brukes til \345 betale for PayPal-kj\370p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\345 PayPal-kontoen din, g\345r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\345ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Vi fors\370ker f\370rst \345 betale med PayPal-saldoen din. Hvis det ikke er nok penger p\345 den, fors\370ker vi \345 bruke bankkontoen din, PayPal Credit, betalingskort og/eller eCheck, i den viste rekkef\370lgen.</p><p>Hvis du vil avbryte denne avtalen, g\345r du til www.paypal.com <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Det kan v\346re n\370dvendig med en liten betalingsgodkjenning for \345 kontrollere at PayPal-kontoen din kan belastes i fremtiden. Godkjenningen blir avbrutt, og du belastes ikke.</p>");
        b.put("LOG_IN_TO_PAYPAL|AU", "Logg p\345 med PayPal");
        b.put("LOG_IN_TO_PAYPAL|GB", "Logg p\345 med PayPal");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din og klikker p\345 tannhjulikonet. G\345 til <strong>Sikkerhet</strong>, velg <strong>Logg p\345 med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din og klikker p\345 tannhjulikonet. G\345 til <strong>Sikkerhet</strong>, velg <strong>Logg p\345 med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din og klikker p\345 tannhjulikonet. G\345 til <strong>Sikkerhet</strong>, velg <strong>Logg p\345 med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, klikker p\345 tannhjulikonet \370verst til h\370yre, velger <strong>Sikkerhet</strong>, <strong>Logg p\345 med PayPal</strong> og fjerner forhandleren. Hvis du fortsatt bruker den tidligere versjonen av nettstedet, g\345r du til <strong>Min profil</strong>, velger <strong>Mine kontoinnstillinger</strong>, <strong>Logg p\345 med PayPal</strong> og fjerner forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, g\345r til <strong>Profil</strong>-innstillingene, <strong>Logg p\345 med PayPal</strong> og fjerner denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.it, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.ru, klikker p\345 tannhjulikonet \370verst til h\370yre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg p\345 med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 PayPal-kontoen din, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.tr, klikker p\345 tannhjulikonet \370verst til h\370yre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg p\345 med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Logg p\345 med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du p\345 paypal.com, g\345r til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg p\345 med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        c.put("AMOUNT_MISMATCH", "Totalbel\370pet for varene i handlekurven samsvarer ikke med kj\370pesummen.");
        c.put("AUTHORIZATION_ALREADY_COMPLETED", "Denne godkjenningen er allerede fullf\370rt.");
        c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkjenningen er i et stadium som ikke kan bli annullert.");
        c.put("AUTHORIZATION_EXPIRED", "Godkjenning utl\370pt.");
        c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Den forespurte godkjennings-IDen finnes ikke.");
        c.put("AUTHORIZATION_VOIDED", "Godkjenningen din er annullert.");
        c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Kan bare godkjenne den opprinnelige godkjenningen, ikke en ny godkjenning.");
        c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ny godkjenning er ikke tillatt innenfor pr\370veperioden.");
        c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Bel\370pet overskrider den tillatte grensen.");
        c.put("CARD_TOKEN_PAYER_MISMATCH", "F\345r ikke tilgang til lagret kortinformasjonen.");
        c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortopplysningene er ugyldige. Vi ber deg korrigere og sende inn p\345 nytt.");
        c.put("CREDIT_CARD_REFUSED", "Kortet ble avvist.");
        c.put("CURRENCY_MISMATCH", "Valuta for innhentingen m\345 v\346re lik valutaen for godkjenning.");
        c.put("CURRENCY_NOT_ALLOWED", "Denne valutaen st\370ttes for \370yeblikket ikke av PayPal.");
        c.put("DATA_RETRIEVAL", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("DUPLICATE_REQUEST_ID", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("EXPIRED_CREDIT_CARD", "Kortet er utl\370pt");
        c.put("EXPIRED_CREDIT_CARD_TOKEN", "Informasjonen for dette kortet er ikke lenger registrert.\nVennligst send p\345 nytt.");
        c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funksjonen st\370ttes ikke for denne forhandleren.");
        c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne transaksjonen er allerede delvis refundert.");
        c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "\330yeblikkelig betaling st\370ttes ikke for den forespurte tjenesten.");
        c.put("INSTRUMENT_DECLINED", "Den betalingsmetoden du valgte ble ikke godtatt. Velg en annen betalingsmetode.");
        c.put("INSUFFICIENT_FUNDS", "Kj\370peren kan ikke betale \u2013 ikke nok penger.");
        c.put("INTERNAL_SERVICE_ERROR", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("INVALID_ACCOUNT_NUMBER", "Det kontonummeret finnes ikke.");
        c.put("INVALID_ARGUMENT", "Transaksjon avvist p\345 grunn av et ugyldig parameter");
        c.put("INVALID_CITY_STATE_ZIP", "Ugyldig kombinasjon for poststed/land/postnummerkombinasjon.");
        c.put("INVALID_FACILITATOR_CONFIGURATION", "Denne transaksjonen kan ikke behandles p\345 grunn av en ugyldig systeminnretningskonfigurasjon.");
        c.put("INVALID_PAYER_ID", "Systemfeil (ugyldig betaler-id). Pr\370v p\345 nytt senere.");
        c.put("INVALID_RESOURCE_ID", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("PAYEE_ACCOUNT_INVALID", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Selgeren kan for \370yeblikket ikke motta betalinger.");
        c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        c.put("PAYEE_ACCOUNT_RESTRICTED", "Selgeren kan for \370yeblikket ikke motta betalinger.");
        c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Kontoen din er l\345st eller avsluttet.");
        c.put("PAYER_ACCOUNT_RESTRICTED", "Kontoen din er begrenset.");
        c.put("PAYER_CANNOT_PAY", "Du kan ikke betale for denne transaksjonen med PayPal.");
        c.put("PAYER_EMPTY_BILLING_ADDRESS", "Det er n\370dvendig med en faktureringsadresse ved betalingskorttransaksjoner utenfor PayPal.");
        c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "F\345r ikke tilgang til lagret kortinformasjonen.");
        c.put("PAYMENT_APPROVAL_EXPIRED", "Betalingsgodkjenningen er utl\370pt.");
        c.put("PAYMENT_EXPIRED", "Betalingen er utl\370pt.");
        c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godtatt betalingen.");
        c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal-foresp\370rselen er ugyldig. Pr\370v p\345 nytt senere.");
        c.put("PAYMENT_STATE_INVALID", "Denne foresp\370rselen er ugyldig p\345 grunn av gjeldende status for betalingen.");
        c.put("PERMISSION_DENIED", "Ingen tillatelse til den forespurte operasjonen.");
        c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den forespurte refusjonen overskrider bel\370pet for den opprinnelige transaksjonen.");
        c.put("REFUND_TIME_LIMIT_EXCEEDED", "Denne transaksjonen er for gammel til at den kan refunderes.");
        c.put("REQUIRED_SCOPE_MISSING", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("TOO_MANY_REAUTHORIZATIONS", "Ingen flere nye godkjenninger er tillatt for denne godkjenningen.");
        c.put("TRANSACTION_ALREADY_REFUNDED", "Denne transaksjonen er allerede refundert.");
        c.put("TRANSACTION_LIMIT_EXCEEDED", "Bel\370pet overskrider den tillatte grensen.");
        c.put("TRANSACTION_REFUSED", "Transaksjonen ble avvist.");
        c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaksjonen ble avvist.");
        c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Forhandlerprofilen er innstilt til \345 automatisk tilbakevise visse transaksjoner.");
        c.put("UNKNOWN_ERROR", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("UNSUPPORTED_PAYEE_COUNTRY", "Landet st\370ttes ikke.");
        c.put("VALIDATION_ERROR", "Betalingsinformasjonen er ugyldig. Vi ber deg korrigere og sende inn p\345 nytt.");
        c.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede annullert, utl\370pt eller fullf\370rt.");
        c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maksimalt antall tillatte godkjenninger for bestillingen er n\345dd.");
        c.put("ORDER_VOIDED", "Bestillingen er blitt annullert.");
        c.put("ORDER_CANNOT_BE_VOIDED", "Det er ikke mulig \345 annullere bestillingen i denne delen av prosessen.");
        c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("UNAUTHORIZED_PAYMENT", "Forhandleren godtar ikke betalinger av denne typen.");
        c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta ikke st\370ttet for korttypen.");
        c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen st\370ttes ikke.");
        c.put("ADDRESS_ADDITION_ERROR", "Det oppstod et problem i l\370pet av prosessen med \345 legge til en forsendelsesadresse i PayPal-kontoen.");
        c.put("DUPLICATE_TRANSACTION", "Duplikattransaksjon.");
        c.put("INVALID_SHIPPING_ADDRESS", "Den oppgitte leveringsadressen er ikke gyldig.");
        c.put("PAYMENT_CREATION_ERROR", "Det oppsto et problem med opprettelsen av denne betalingen. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Det oppsto et problem med opprettelsen av denne betalingen \u2013 kortet ditt er utl\370pt. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Det oppsto et problem med opprettelsen av denne betalingen \u2013 direktebetaling kreves, f.eks. med et kredittkort. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Det oppsto et problem med opprettelsen av denne betalingen \u2013 kortet m\345 bekreftes. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Det oppsto et problem med opprettelsen av denne betalingen \u2013 denne appen krever at kontoen din inneholder et telefonnummer. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Det oppsto et problem med opprettelsen av denne betalingen \u2013 kontoen m\345 ha en gyldig betalingskilde, f.eks. en bankkonto eller et betalingskort. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Det oppsto et problem med opprettelsen av denne betalingen \u2013 saldoen din er i minus. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Det oppsto et problem med opprettelsen av denne betalingen \u2013 sendegrensen din er n\345dd. G\345 til PayPal-nettstedet for \345 kontrollere kontoen din.");
        c.put("AUTH_RC_RISK_FAILURE", "Avvist grunnet risiko.");
        c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkjent.");
        c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkjent.");
        c.put("invalid_user", "Feil brukernavn/passord. Pr\370v p\345 nytt.");
        c.put("locked_user", "PayPal-kontoen din er midlertidig sperret. Pr\370v p\345 nytt senere, eller g\345 til www.paypal.com for \345 l\345se opp PayPal-kontoen din med en gang.");
        c.put("max_attempts_exceeded", "For mange mislykkede p\345loggingsfors\370k. Pr\370v p\345 nytt senere.");
        c.put("invalid_request", "Det har oppst\345tt en feil.");
        c.put("unauthorized_client", "Ikke godkjent foresp\370rsel.");
        c.put("access_denied", "Ikke godkjent foresp\370rsel.");
        c.put("unsupported_response_type", "Det har oppst\345tt en feil.");
        c.put("invalid_scope", "Ikke godkjent foresp\370rsel.");
        c.put("server_error", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("temporarily_unavailable", "Systemfeil. Pr\370v p\345 nytt senere.");
        c.put("stepup_required", "Det er ikke mulig \345 logge p\345 akkurat n\345. Pr\370v p\345 nytt senere, eller g\345 til www.paypal.com for \345 l\370se eventuelle sikkerhetsproblemer med kontoen din.");
    }

    public final String a()
    {
        return "nb";
    }

    public final String a(Enum enum, String s)
    {
        enum = (cG)enum;
        s = (new StringBuilder()).append(enum.toString()).append("|").append(s).toString();
        if (b.containsKey(s))
        {
            return (String)b.get(s);
        } else
        {
            return (String)a.get(enum);
        }
    }

    public final String a(String s)
    {
        return (String)c.get(s);
    }

}
